name: CI
on: 
  push:
  pull_request:
  workflow_call:
jobs:
  snapshots:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-12
          #- windows-latest
    runs-on: ${{ matrix.os }}
    env:
      CARGO_WASIX_OFFLINE: '1'
    steps:
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check out
        uses: actions/checkout@v3

      - name: Check out
        uses: actions/checkout@v3
        with:
          repository: 'john-sharratt/wasmer'
          ref: os
          path: ./build/wasmer

      - name: Check out
        uses: actions/checkout@v3
        with:
          repository: 'wasmerio/pirita-john'
          path: ./build/pirita
          ref: deploy

      - name: Install wasmer
        shell: bash
        run: |
          cargo install --path ./build/wasmer --features cranelift,compiler,debug wasmer-cli

      - name: Install cargo-wasix
        shell: bash
        run: |
          cargo install --git https://github.com/wasmerio/cargo-wasix cargo-wasix

      - name: Download wasix toolchain
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN  }}"
        run: |
          cargo wasix download-toolchain

      - name: Run snapshot tests
        shell: bash
        run: |
          cd snapshots
          cargo test

